# Generated by Django 4.2.4 on 2023-08-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(null=True, upload_to='obras/'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='descripcion',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='obra',
            name='historia',
            field=models.TextField(max_length=150),
        ),
    ]
