# Generated by Django 4.2.4 on 2023-08-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_alter_obra_descripcion_alter_obra_historia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/imagenes/obras/'),
        ),
    ]
